require: rubocop-rails

AllCops:
  NewCops: enable

Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'db/migrate/**/*.rb'
    - 'scripts/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*.rb'

Naming/VariableNumber:
  Exclude:
    - 'scripts/**/*.rb' # Scripts often use variables like j1, j2, etc.
